import json

dictionary = {
  "Reward": "보상",
  "PAUSED": "일시 정지됨",
  "Destination wallet": "목적지 지갑",
  "Refreshed dashboard": "대시보드 새로고침됨",
  "Lower cap to": "한도를 다음으로 낮추기:",
  "/api/user/profile": "/api/user/profile",
  "OWNER ACCESS": "소유자 권한",
  "Admin Logs": "관리자 로그",
  "per certificate": "인증서 당",
  "More languages coming soon — Japanese, Chinese, Thai": "곧 더 많은 언어가 지원됩니다 — 일본어, 중국어, 태국어",
  "Lock remaining": "남은 락업",
  "Held by Owners": "소유자가 보유함",
  "Update URI": "URI 업데이트",
  "Paused": "일시 정지됨",
  "Wallet address": "지갑 주소",
  "Save rounds": "라운드 저장",
  "Airdrop claimed": "에어드롭 수령됨",
  "Confirming...": "확인 중...",
  "View on BscScan": "BscScan에서 보기",
  "Submit Proposal": "제안서 제출",
  "Refreshing...": "새로고침 중...",
  "ID": "ID",
  "Manual Override": "수동 재정의",
  "Contributing to the Binance Smart Chain ecosystem": "바이낸스 스마트 체인 생태계에 기여",
  "Reserve inventory": "재고 예약",
  "Roadmap": "로드맵",
  "Partners & Ecosystem Projects": "파트너 및 생태계 프로젝트",
  "Governance Proposals": "거버넌스 제안",
  "can only be lowered, never raised": "낮출 수만 있으며, 결코 높일 수 없습니다",
  "Creating New": "새로 생성 중",
  "Link2E Referral Program": "Link2E 추천 프로그램",
  "Remaining Locked": "남은 락업 수량",
  "Loading artwork…": "아트워크 로딩 중…",
  "Refresh": "새로고침",
  "Token Holdings": "토큰 보유량",
  "Copy": "복사",
  "editable by Safe": "Safe로 편집 가능",
  "Complete payment by card or PG; the team confirms the order.": "카드 또는 PG로 결제를 완료하면 팀에서 주문을 확인합니다.",
  "Launch App": "앱 실행",
  "Grant MINTER_ROLE": "MINTER_ROLE 부여",
  "Reserve": "예약",
  "Status": "상태",
  "Prefix": "접두사",
  "Units": "단위",
  "Confirm pause state change for the whole collection?": "전체 컬렉션에 대한 일시 정지 상태 변경을 확인하시겠습니까?",
  "Open": "열기",
  "Pending": "대기 중",
  "Serial format": "일련번호 형식",
  "Team Allocation": "팀 할당",
  "Remove round": "라운드 제거",
  "The ceiling the royalty setter is checked against.": "로열티 설정자가 확인하는 상한선입니다.",
  "Secondary Sale Royalty": "2차 판매 로열티",
  "Exact serial issuance": "정확한 일련번호 발행",
  "Metadata": "메타데이터",
  "Holder": "보유자",
  "Locked · burn-linked": "잠금 · 소각 연계",
  "Choose your preferred display language.": "선호하는 언어를 선택하세요.",
  "Notifications": "알림",
  "Certificate required": "인증서 필요",
  "Royalty": "로열티",
  "Preview": "미리보기",
  "Trigger Airdrop": "에어드롭 실행",
  "Compensation": "보상",
  "Owner Panel": "소유자 패널",
  "Claim failed": "수령 실패",
  "Creator DAO Account": "크리에이터 DAO 계정",
  "burned": "소각됨",
  "Must end with a slash.": "슬래시로 끝나야 합니다.",
  "How to obtain a certificate": "인증서를 발급받는 방법",
  "Run this once the card / PG payment for the order is confirmed.": "주문에 대한 카드 / PG 결제가 확인되면 실행하십시오.",
  "Claimable Now": "지금 수령 가능",
  "Membership tier": "멤버십 등급",
  "Emergency Pause": "긴급 일시 정지",
  "Wallet Address": "지갑 주소",
  "Date": "날짜",
  "Remaining": "남음",
  "Submit a purchase application to the Block Label Foundation.": "Block Label 재단에 구매 신청서를 제출하세요.",
  "Issued": "발행됨",
  "Votes Cast": "투표함",
  "Rewards Earned": "획득한 보상",
  "none burned": "소각된 것 없음",
  "Allocated airdrop": "할당된 에어드롭",
  "Unpause": "일시 정지 해제",
  "Issuing Authority": "발행 기관",
  "Access Denied": "접근 거부",
  "Grant": "부여",
  "Metadata freeze": "메타데이터 동결",
  "Current": "현재",
  "Technology & Art,": "기술 및 예술,",
  "Serial range": "일련번호 범위",
  "Operations Wallet (MINTER_ROLE)": "운영 지갑 (MINTER_ROLE)",
  "Only the owner wallet can access this panel.": "소유자 지갑만 이 패널에 접근할 수 있습니다.",
  "Serial format update": "일련번호 형식 업데이트",
  "Pause Contract": "컨트랙트 일시 정지",
  "days": "일",
  "Unlocked (50% burn)": "잠금 해제됨 (50% 소각)",
  "Rounds update": "라운드 업데이트",
  "Royalty ceiling update": "로열티 상한 업데이트",
  "adjustable, hard-limited to 25% in code": "조정 가능, 코드에서 25%로 엄격히 제한됨",
  "DAO Role": "DAO 역할",
  "Staking Reminders": "스테이킹 알림",
  "Failed to authenticate wallet": "지갑 인증 실패",
  "Confirming…": "확인 중…",
  "Referred Wallets": "추천된 지갑",
  "About": "소개",
  "Partners & Ecosystem": "파트너 및 생태계",
  "You're eligible — your round allocation opens soon.": "귀하는 자격이 있습니다 — 라운드 할당이 곧 열립니다.",
  "Application": "신청",
  "Token Allocation": "토큰 할당",
  "Link copied": "링크 복사됨",
  "Issued collection-wide": "전체 컬렉션에 발행됨",
  "Current Language": "현재 언어",
  "Grant to a replacement wallet, or revoke a compromised one.": "대체 지갑에 권한을 부여하거나 손상된 지갑의 권한을 취소하십시오.",
  "Claim confirmed on-chain.": "온체인에서 수령이 확인되었습니다.",
  "Certificates are not live yet": "인증서가 아직 활성화되지 않았습니다.",
  "Collection Settings": "컬렉션 설정",
  "All Types": "모든 유형",
  "Wallet": "지갑",
  "Resources": "자원",
  "Airdrop allocation by round": "라운드별 에어드롭 할당",
  "Type": "유형",
  "Action": "작업",
  "Collection Parameters": "컬렉션 매개변수",
  "Purchase information": "구매 정보",
  "Round": "라운드",
  "cap is lowerable only": "한도는 낮출 수만 있습니다",
  "Minimum Staking Required": "최소 스테이킹 필요",
  "Supply Cap": "공급 한도",
  "Digits": "자릿수",
  "From serial": "시작 일련번호",
  "Quantity": "수량",
  "No certificates issued yet.": "아직 인증서가 발행되지 않았습니다.",
  "Base URI update": "기본 URI 업데이트",
  "Set royalty": "로열티 설정",
  "Your Referral Link": "귀하의 추천 링크",
  "Certificate issuance": "인증서 발행",
  "Your certificates": "귀하의 인증서",
  "Wait for verification to qualify.": "자격을 얻으려면 검증을 기다리세요.",
  "Royalty update": "로열티 업데이트",
  "Artwork unavailable": "아트워크를 사용할 수 없음",
  "Serial number": "일련번호",
  "invalid": "유효하지 않음",
  "Amount ({{SYMBOL}})": "수량 ({{SYMBOL}})",
  "sold out": "매진됨",
  "Metadata base URI": "메타데이터 기본 URI",
  "each": "각각",
  "Will issue": "발행 예정",
  "Issue a specific serial": "특정 일련번호 발행",
  "Employment Type": "고용 형태",
  "Active": "활성",
  "Recruiting Period": "모집 기간",
  "BSC Ecosystem Contribution": "BSC 생태계 기여",
  "recipients": "수신자",
  "Claiming...": "수령 중...",
  "Next Airdrop Date": "다음 에어드롭 날짜",
  "Freeze": "동결",
  "To serial": "끝 일련번호",
  "Claim": "수령",
  "Transaction History": "트랜잭션 내역",
  "used by sequential issue": "순차 발행에 사용됨",
  "Privacy Policy": "개인정보 보호정책",
  "Serial": "일련번호",
  "Revoke MINTER_ROLE": "MINTER_ROLE 취소",
  "Wholesale access granted": "도매 접근 권한 부여됨",
  "Switch Network": "네트워크 전환",
  "ACTIVE": "활성",
  "Connected": "연결됨",
  "Reset": "초기화",
  "Participation History": "참여 내역",
  "Origin": "기원",
  "Authenticity Verified": "진위 검증됨",
  "Settings saved": "설정 저장됨",
  "Estimated Reward": "예상 보상",
  "Freezing metadata is permanent and cannot be undone. Continue?": "메타데이터 동결은 영구적이며 취소할 수 없습니다. 계속하시겠습니까?",
  "Team Burned": "팀 소각됨",
  "Creator DAO Certificates": "크리에이터 DAO 인증서",
  "Total-supply burn progress": "총 공급량 소각 진행률",
  "Maximum royalty percent": "최대 로열티 백분율",
  "Pause collection": "컬렉션 일시 정지",
  "Pause": "일시 정지",
  "Language": "언어",
  "Proposal": "제안",
  "Language Settings": "언어 설정",
  "Your certificate then appears on this page automatically.": "그러면 인증서가 이 페이지에 자동으로 나타납니다.",
  "Batch issuance": "일괄 발행",
  "Wrong Network": "잘못된 네트워크",
  "Search TX hash...": "TX 해시 검색...",
  "TX Hash": "TX 해시",
  "Supply cap reduction": "공급 한도 감소",
  "Save Settings": "설정 저장",
  "Download CSV": "CSV 다운로드",
  "Unpause collection": "컬렉션 일시 정지 해제",
  "Qualified": "자격 있음",
  "NFT Certificate Operations": "NFT 인증서 작업",
  "Buyer BSC wallet": "구매자 BSC 지갑",
  "Set ceiling to": "상한을 다음으로 설정:",
  "Issuance Rounds & BDL Allocation": "발행 라운드 및 BDL 할당",
  "Amount": "수량",
  "Reserve issuance": "예약 발행",
  "CSV Download generation": "CSV 다운로드 생성",
  "max": "최대",
  "Team Vault & Burn": "팀 금고 및 소각",
  "Next Serial": "다음 일련번호",
  "Issue to a Buyer": "구매자에게 발행",
  "Address copied": "주소 복사됨",
  "New maximum supply": "새로운 최대 공급량",
  "Batch issue to many buyers": "여러 구매자에게 일괄 발행",
  "Wallet authenticated successfully": "지갑 인증 성공",
  "Enquiries": "문의",
  "New base URI": "새 기본 URI",
  "Revoke": "취소",
  "Individual Overwrite": "개별 덮어쓰기",
  "Add round": "라운드 추가",
  "Terms": "약관",
  "Entertainment.": "엔터테인먼트.",
  "Certificate contract not configured": "인증서 컨트랙트가 구성되지 않았습니다",
  "Not a valid BSC address": "유효한 BSC 주소가 아닙니다",
  "certificates": "인증서",
  "Highest Serials Issued": "발행된 최고 일련번호",
  "frozen (immutable)": "동결됨 (변경 불가)",
  "Current ceiling": "현재 상한",
  "Affects on-chain display only — regenerate the metadata to match.": "온체인 표시에만 영향을 미칩니다 — 일치하도록 메타데이터를 다시 생성하십시오.",
  "Royalty Ceiling": "로열티 상한",
  "Disconnect": "연결 해제",
  "Your Claim": "당신의 수령액",
  "View on Block Label": "Block Label에서 보기",
  "Issuance Rounds": "발행 라운드",
  "Issue": "발행",
  "Price Alerts": "가격 알림",
  "Read-only — these actions require the Safe multisig, not the operations wallet.": "읽기 전용 — 이러한 작업은 운영 지갑이 아닌 Safe 멀티시그가 필요합니다.",
  "Airdrop Alerts": "에어드롭 알림",
  "Back to List": "목록으로 돌아가기",
  "Team": "팀",
  "Airdrop distributor not deployed yet.": "에어드롭 배포자가 아직 배포되지 않았습니다.",
  "Apply Language": "언어 적용",
  "One address per line. Serials are assigned in the order listed.": "한 줄에 하나의 주소. 나열된 순서대로 일련번호가 할당됩니다.",
  "Percent": "백분율",
  "The Creator DAO Certificate collection has not been deployed to this network yet.": "크리에이터 DAO 인증서 컬렉션이 이 네트워크에 아직 배포되지 않았습니다.",
  "All your on-chain activity in one place.": "모든 온체인 활동을 한곳에서 확인하세요.",
  "All contact channels": "모든 연락 채널",
  "Dashboard": "대시보드",
  "Receiver": "수신자",
  "Save serial format": "일련번호 형식 저장",
  "OPERATIONS": "운영",
  "Verified": "인증됨",
  "SAFE ADMIN": "안전 관리자",
  "{{BRAND}} is built on the BNB Chain.": "{{BRAND}}는 BNB 체인에 구축되어 있습니다.",
  "Metadata is frozen — this can no longer change.": "메타데이터가 동결되었습니다 — 더 이상 변경할 수 없습니다.",
  "Token Controls": "토큰 제어",
  "Signed by the Foundation Safe multisig.": "재단 Safe 멀티시그에 의해 서명되었습니다.",
  "Serial Number Format": "일련번호 형식",
  "Block Label Creator DAO Certificate Test": "블록 라벨 크리에이터 DAO 인증서 테스트"
}

with open('src/lib/i18n.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

lines = []
for k, v in dictionary.items():
    if f'"{k}":' not in content:
        lines.append(f'  "{k}": "{v}",')

if lines:
    block = '\n' + '\n'.join(lines) + '\n'
    content = content.replace('};\n\nexport function I18nProvider', block + '};\n\nexport function I18nProvider')
    with open('src/lib/i18n.tsx', 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Added {len(lines)} missing translations!")
else:
    print("Already present.")
