/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";

import { Route as TransactionsRouteImport } from "./routes/transactions";
import { Route as ReferralRouteImport } from "./routes/referral";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as LanguageRouteImport } from "./routes/language";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ConnectRouteImport } from "./routes/connect";
import { Route as AirdropRouteImport } from "./routes/airdrop";
import { Route as NftAdminRouteImport } from "./routes/nft-admin";
import { Route as CertificatesRouteImport } from "./routes/certificates";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as BusinessRouteImport } from "./routes/business";
import { Route as TechnologyRouteImport } from "./routes/technology";
import { Route as RoadmapRouteImport } from "./routes/roadmap";
import { Route as CareersRouteImport } from "./routes/careers";
import { Route as DealersRouteImport } from "./routes/dealers";
import { Route as TokenRouteImport } from "./routes/token";
import { Route as NewsRouteImport } from "./routes/news";
import { Route as NoticesRouteImport } from "./routes/notices";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as DealerInquiryRouteImport } from "./routes/dealer-inquiry";
import { Route as TabletInquiryRouteImport } from "./routes/tablet-inquiry";
import { Route as CareersAiInstructorRouteImport } from "./routes/careers-ai-instructor";
import { Route as CareersDancersChoreographersRouteImport } from "./routes/careers-dancers-choreographers";
import { Route as CareersAiVideoContentCreatorRouteImport } from "./routes/careers-ai-video-content-creator";
import { Route as CareersActorsRouteImport } from "./routes/careers-actors";
import { Route as NewsMoripeSamsungB2bRouteImport } from "./routes/news-moripe-samsung-b2b";
import { Route as NewsDellaBalladProjectRouteImport } from "./routes/news-della-ballad-project";
import { Route as NoticesDemoSourcingRouteImport } from "./routes/notices-demo-sourcing";
import { Route as NoticesWebsiteLaunchRouteImport } from "./routes/notices-website-launch";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";


const TransactionsRoute = TransactionsRouteImport.update({
  id: "/transactions",
  path: "/transactions",
  getParentRoute: () => rootRouteImport,
} as any);
const ReferralRoute = ReferralRouteImport.update({
  id: "/referral",
  path: "/referral",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const LanguageRoute = LanguageRouteImport.update({
  id: "/language",
  path: "/language",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ConnectRoute = ConnectRouteImport.update({
  id: "/connect",
  path: "/connect",
  getParentRoute: () => rootRouteImport,
} as any);
const AirdropRoute = AirdropRouteImport.update({
  id: "/airdrop",
  path: "/airdrop",
  getParentRoute: () => rootRouteImport,
} as any);
const NftAdminRoute = NftAdminRouteImport.update({
  id: "/nft-admin",
  path: "/nft-admin",
  getParentRoute: () => rootRouteImport,
} as any);
const CertificatesRoute = CertificatesRouteImport.update({
  id: "/certificates",
  path: "/certificates",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const BusinessRoute = BusinessRouteImport.update({
  id: "/business",
  path: "/business",
  getParentRoute: () => rootRouteImport,
} as any);
const TechnologyRoute = TechnologyRouteImport.update({
  id: "/technology",
  path: "/technology",
  getParentRoute: () => rootRouteImport,
} as any);
const RoadmapRoute = RoadmapRouteImport.update({
  id: "/roadmap",
  path: "/roadmap",
  getParentRoute: () => rootRouteImport,
} as any);
const CareersRoute = CareersRouteImport.update({
  id: "/careers",
  path: "/careers",
  getParentRoute: () => rootRouteImport,
} as any);
const DealersRoute = DealersRouteImport.update({
  id: "/dealers",
  path: "/dealers",
  getParentRoute: () => rootRouteImport,
} as any);
const TokenRoute = TokenRouteImport.update({
  id: "/token",
  path: "/token",
  getParentRoute: () => rootRouteImport,
} as any);
const NewsRoute = NewsRouteImport.update({
  id: "/news",
  path: "/news",
  getParentRoute: () => rootRouteImport,
} as any);
const NoticesRoute = NoticesRouteImport.update({
  id: "/notices",
  path: "/notices",
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any);
const DealerInquiryRoute = DealerInquiryRouteImport.update({
  id: "/dealer-inquiry",
  path: "/dealer-inquiry",
  getParentRoute: () => rootRouteImport,
} as any);
const TabletInquiryRoute = TabletInquiryRouteImport.update({
  id: "/tablet-inquiry",
  path: "/tablet-inquiry",
  getParentRoute: () => rootRouteImport,
} as any);
const CareersAiInstructorRoute = CareersAiInstructorRouteImport.update({
  id: "/careers/ai-instructor",
  path: "/careers/ai-instructor",
  getParentRoute: () => rootRouteImport,
} as any);
const CareersDancersChoreographersRoute = CareersDancersChoreographersRouteImport.update({
  id: "/careers/dancers-choreographers",
  path: "/careers/dancers-choreographers",
  getParentRoute: () => rootRouteImport,
} as any);
const CareersAiVideoContentCreatorRoute = CareersAiVideoContentCreatorRouteImport.update({
  id: "/careers/ai-video-content-creator",
  path: "/careers/ai-video-content-creator",
  getParentRoute: () => rootRouteImport,
} as any);
const CareersActorsRoute = CareersActorsRouteImport.update({
  id: "/careers/actors",
  path: "/careers/actors",
  getParentRoute: () => rootRouteImport,
} as any);
const NewsMoripeSamsungB2bRoute = NewsMoripeSamsungB2bRouteImport.update({
  id: "/news/moripe-samsung-b2b",
  path: "/news/moripe-samsung-b2b",
  getParentRoute: () => rootRouteImport,
} as any);
const NewsDellaBalladProjectRoute = NewsDellaBalladProjectRouteImport.update({
  id: "/news/della-ballad-project",
  path: "/news/della-ballad-project",
  getParentRoute: () => rootRouteImport,
} as any);
const NoticesDemoSourcingRoute = NoticesDemoSourcingRouteImport.update({
  id: "/notices/demo-sourcing",
  path: "/notices/demo-sourcing",
  getParentRoute: () => rootRouteImport,
} as any);
const NoticesWebsiteLaunchRoute = NoticesWebsiteLaunchRouteImport.update({
  id: "/notices/website-launch",
  path: "/notices/website-launch",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/business": typeof BusinessRoute;
  "/technology": typeof TechnologyRoute;
  "/roadmap": typeof RoadmapRoute;
  "/careers": typeof CareersRoute;
  "/dealers": typeof DealersRoute;
  "/token": typeof TokenRoute;
  "/news": typeof NewsRoute;
  "/notices": typeof NoticesRoute;
  "/contact": typeof ContactRoute;
  "/dealer-inquiry": typeof DealerInquiryRoute;
  "/tablet-inquiry": typeof TabletInquiryRoute;
  "/careers/ai-instructor": typeof CareersAiInstructorRoute;
  "/careers/dancers-choreographers": typeof CareersDancersChoreographersRoute;
  "/careers/ai-video-content-creator": typeof CareersAiVideoContentCreatorRoute;
  "/careers/actors": typeof CareersActorsRoute;
  "/news/moripe-samsung-b2b": typeof NewsMoripeSamsungB2bRoute;
  "/news/della-ballad-project": typeof NewsDellaBalladProjectRoute;
  "/notices/demo-sourcing": typeof NoticesDemoSourcingRoute;
  "/notices/website-launch": typeof NoticesWebsiteLaunchRoute;
  "/about": typeof AboutRoute;
  "/admin": typeof AdminRoute;
  "/airdrop": typeof AirdropRoute;
  "/certificates": typeof CertificatesRoute;
  "/nft-admin": typeof NftAdminRoute;
  "/connect": typeof ConnectRoute;
  "/dashboard": typeof DashboardRoute;
  "/language": typeof LanguageRoute;
  "/profile": typeof ProfileRoute;
  "/referral": typeof ReferralRoute;
  "/transactions": typeof TransactionsRoute;

}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/business": typeof BusinessRoute;
  "/technology": typeof TechnologyRoute;
  "/roadmap": typeof RoadmapRoute;
  "/careers": typeof CareersRoute;
  "/dealers": typeof DealersRoute;
  "/token": typeof TokenRoute;
  "/news": typeof NewsRoute;
  "/notices": typeof NoticesRoute;
  "/contact": typeof ContactRoute;
  "/dealer-inquiry": typeof DealerInquiryRoute;
  "/tablet-inquiry": typeof TabletInquiryRoute;
  "/careers/ai-instructor": typeof CareersAiInstructorRoute;
  "/careers/dancers-choreographers": typeof CareersDancersChoreographersRoute;
  "/careers/ai-video-content-creator": typeof CareersAiVideoContentCreatorRoute;
  "/careers/actors": typeof CareersActorsRoute;
  "/news/moripe-samsung-b2b": typeof NewsMoripeSamsungB2bRoute;
  "/news/della-ballad-project": typeof NewsDellaBalladProjectRoute;
  "/notices/demo-sourcing": typeof NoticesDemoSourcingRoute;
  "/notices/website-launch": typeof NoticesWebsiteLaunchRoute;
  "/about": typeof AboutRoute;
  "/admin": typeof AdminRoute;
  "/airdrop": typeof AirdropRoute;
  "/certificates": typeof CertificatesRoute;
  "/nft-admin": typeof NftAdminRoute;
  "/connect": typeof ConnectRoute;
  "/dashboard": typeof DashboardRoute;
  "/language": typeof LanguageRoute;
  "/profile": typeof ProfileRoute;
  "/referral": typeof ReferralRoute;
  "/transactions": typeof TransactionsRoute;

}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/business": typeof BusinessRoute;
  "/technology": typeof TechnologyRoute;
  "/roadmap": typeof RoadmapRoute;
  "/careers": typeof CareersRoute;
  "/dealers": typeof DealersRoute;
  "/token": typeof TokenRoute;
  "/news": typeof NewsRoute;
  "/notices": typeof NoticesRoute;
  "/contact": typeof ContactRoute;
  "/dealer-inquiry": typeof DealerInquiryRoute;
  "/tablet-inquiry": typeof TabletInquiryRoute;
  "/careers/ai-instructor": typeof CareersAiInstructorRoute;
  "/careers/dancers-choreographers": typeof CareersDancersChoreographersRoute;
  "/careers/ai-video-content-creator": typeof CareersAiVideoContentCreatorRoute;
  "/careers/actors": typeof CareersActorsRoute;
  "/news/moripe-samsung-b2b": typeof NewsMoripeSamsungB2bRoute;
  "/news/della-ballad-project": typeof NewsDellaBalladProjectRoute;
  "/notices/demo-sourcing": typeof NoticesDemoSourcingRoute;
  "/notices/website-launch": typeof NoticesWebsiteLaunchRoute;
  "/about": typeof AboutRoute;
  "/admin": typeof AdminRoute;
  "/airdrop": typeof AirdropRoute;
  "/certificates": typeof CertificatesRoute;
  "/nft-admin": typeof NftAdminRoute;
  "/connect": typeof ConnectRoute;
  "/dashboard": typeof DashboardRoute;
  "/language": typeof LanguageRoute;
  "/profile": typeof ProfileRoute;
  "/referral": typeof ReferralRoute;
  "/transactions": typeof TransactionsRoute;

}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/business"
    | "/technology"
    | "/roadmap"
    | "/careers"
    | "/dealers"
    | "/token"
    | "/news"
    | "/notices"
    | "/contact"
    | "/dealer-inquiry"
    | "/tablet-inquiry"
    | "/careers/ai-instructor"
    | "/careers/dancers-choreographers"
    | "/careers/ai-video-content-creator"
    | "/careers/actors"
    | "/news/moripe-samsung-b2b"
    | "/news/della-ballad-project"
    | "/notices/demo-sourcing"
    | "/notices/website-launch"
    | "/about"
    | "/admin"
    | "/airdrop"
    | "/certificates"
    | "/nft-admin"
    | "/connect"
    | "/dashboard"
    | "/language"
    | "/profile"
    | "/referral"
    | "/transactions"

  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/business"
    | "/technology"
    | "/roadmap"
    | "/careers"
    | "/dealers"
    | "/token"
    | "/news"
    | "/notices"
    | "/contact"
    | "/dealer-inquiry"
    | "/tablet-inquiry"
    | "/careers/ai-instructor"
    | "/careers/dancers-choreographers"
    | "/careers/ai-video-content-creator"
    | "/careers/actors"
    | "/news/moripe-samsung-b2b"
    | "/news/della-ballad-project"
    | "/notices/demo-sourcing"
    | "/notices/website-launch"
    | "/about"
    | "/admin"
    | "/airdrop"
    | "/certificates"
    | "/nft-admin"
    | "/connect"
    | "/dashboard"
    | "/language"
    | "/profile"
    | "/referral"
    | "/transactions"

  id:
    | "__root__"
    | "/"
    | "/business"
    | "/technology"
    | "/roadmap"
    | "/careers"
    | "/dealers"
    | "/token"
    | "/news"
    | "/notices"
    | "/contact"
    | "/dealer-inquiry"
    | "/tablet-inquiry"
    | "/careers/ai-instructor"
    | "/careers/dancers-choreographers"
    | "/careers/ai-video-content-creator"
    | "/careers/actors"
    | "/news/moripe-samsung-b2b"
    | "/news/della-ballad-project"
    | "/notices/demo-sourcing"
    | "/notices/website-launch"
    | "/about"
    | "/admin"
    | "/airdrop"
    | "/certificates"
    | "/nft-admin"
    | "/connect"
    | "/dashboard"
    | "/language"
    | "/profile"
    | "/referral"
    | "/transactions"

  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BusinessRoute: typeof BusinessRoute;
  TechnologyRoute: typeof TechnologyRoute;
  RoadmapRoute: typeof RoadmapRoute;
  CareersRoute: typeof CareersRoute;
  DealersRoute: typeof DealersRoute;
  TokenRoute: typeof TokenRoute;
  NewsRoute: typeof NewsRoute;
  NoticesRoute: typeof NoticesRoute;
  ContactRoute: typeof ContactRoute;
  DealerInquiryRoute: typeof DealerInquiryRoute;
  TabletInquiryRoute: typeof TabletInquiryRoute;
  CareersAiInstructorRoute: typeof CareersAiInstructorRoute;
  CareersDancersChoreographersRoute: typeof CareersDancersChoreographersRoute;
  CareersAiVideoContentCreatorRoute: typeof CareersAiVideoContentCreatorRoute;
  CareersActorsRoute: typeof CareersActorsRoute;
  NewsMoripeSamsungB2bRoute: typeof NewsMoripeSamsungB2bRoute;
  NewsDellaBalladProjectRoute: typeof NewsDellaBalladProjectRoute;
  NoticesDemoSourcingRoute: typeof NoticesDemoSourcingRoute;
  NoticesWebsiteLaunchRoute: typeof NoticesWebsiteLaunchRoute;
  AboutRoute: typeof AboutRoute;
  AdminRoute: typeof AdminRoute;
  AirdropRoute: typeof AirdropRoute;
  CertificatesRoute: typeof CertificatesRoute;
  NftAdminRoute: typeof NftAdminRoute;
  ConnectRoute: typeof ConnectRoute;
  DashboardRoute: typeof DashboardRoute;
  LanguageRoute: typeof LanguageRoute;
  ProfileRoute: typeof ProfileRoute;
  ReferralRoute: typeof ReferralRoute;
  TransactionsRoute: typeof TransactionsRoute;

}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {

    "/transactions": {
      id: "/transactions";
      path: "/transactions";
      fullPath: "/transactions";
      preLoaderRoute: typeof TransactionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/referral": {
      id: "/referral";
      path: "/referral";
      fullPath: "/referral";
      preLoaderRoute: typeof ReferralRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/language": {
      id: "/language";
      path: "/language";
      fullPath: "/language";
      preLoaderRoute: typeof LanguageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/connect": {
      id: "/connect";
      path: "/connect";
      fullPath: "/connect";
      preLoaderRoute: typeof ConnectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/nft-admin": {
      id: "/nft-admin";
      path: "/nft-admin";
      fullPath: "/nft-admin";
      preLoaderRoute: typeof NftAdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/certificates": {
      id: "/certificates";
      path: "/certificates";
      fullPath: "/certificates";
      preLoaderRoute: typeof CertificatesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/airdrop": {
      id: "/airdrop";
      path: "/airdrop";
      fullPath: "/airdrop";
      preLoaderRoute: typeof AirdropRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/business": {
      id: "/business";
      path: "/business";
      fullPath: "/business";
      preLoaderRoute: typeof BusinessRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/technology": {
      id: "/technology";
      path: "/technology";
      fullPath: "/technology";
      preLoaderRoute: typeof TechnologyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/roadmap": {
      id: "/roadmap";
      path: "/roadmap";
      fullPath: "/roadmap";
      preLoaderRoute: typeof RoadmapRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/careers": {
      id: "/careers";
      path: "/careers";
      fullPath: "/careers";
      preLoaderRoute: typeof CareersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dealers": {
      id: "/dealers";
      path: "/dealers";
      fullPath: "/dealers";
      preLoaderRoute: typeof DealersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/token": {
      id: "/token";
      path: "/token";
      fullPath: "/token";
      preLoaderRoute: typeof TokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/news": {
      id: "/news";
      path: "/news";
      fullPath: "/news";
      preLoaderRoute: typeof NewsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/notices": {
      id: "/notices";
      path: "/notices";
      fullPath: "/notices";
      preLoaderRoute: typeof NoticesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dealer-inquiry": {
      id: "/dealer-inquiry";
      path: "/dealer-inquiry";
      fullPath: "/dealer-inquiry";
      preLoaderRoute: typeof DealerInquiryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tablet-inquiry": {
      id: "/tablet-inquiry";
      path: "/tablet-inquiry";
      fullPath: "/tablet-inquiry";
      preLoaderRoute: typeof TabletInquiryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/careers/ai-instructor": {
      id: "/careers/ai-instructor";
      path: "/careers/ai-instructor";
      fullPath: "/careers/ai-instructor";
      preLoaderRoute: typeof CareersAiInstructorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/careers/dancers-choreographers": {
      id: "/careers/dancers-choreographers";
      path: "/careers/dancers-choreographers";
      fullPath: "/careers/dancers-choreographers";
      preLoaderRoute: typeof CareersDancersChoreographersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/careers/ai-video-content-creator": {
      id: "/careers/ai-video-content-creator";
      path: "/careers/ai-video-content-creator";
      fullPath: "/careers/ai-video-content-creator";
      preLoaderRoute: typeof CareersAiVideoContentCreatorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/careers/actors": {
      id: "/careers/actors";
      path: "/careers/actors";
      fullPath: "/careers/actors";
      preLoaderRoute: typeof CareersActorsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/news/moripe-samsung-b2b": {
      id: "/news/moripe-samsung-b2b";
      path: "/news/moripe-samsung-b2b";
      fullPath: "/news/moripe-samsung-b2b";
      preLoaderRoute: typeof NewsMoripeSamsungB2bRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/news/della-ballad-project": {
      id: "/news/della-ballad-project";
      path: "/news/della-ballad-project";
      fullPath: "/news/della-ballad-project";
      preLoaderRoute: typeof NewsDellaBalladProjectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/notices/demo-sourcing": {
      id: "/notices/demo-sourcing";
      path: "/notices/demo-sourcing";
      fullPath: "/notices/demo-sourcing";
      preLoaderRoute: typeof NoticesDemoSourcingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/notices/website-launch": {
      id: "/notices/website-launch";
      path: "/notices/website-launch";
      fullPath: "/notices/website-launch";
      preLoaderRoute: typeof NoticesWebsiteLaunchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRoute,
  TechnologyRoute: TechnologyRoute,
  RoadmapRoute: RoadmapRoute,
  CareersRoute: CareersRoute,
  DealersRoute: DealersRoute,
  TokenRoute: TokenRoute,
  NewsRoute: NewsRoute,
  NoticesRoute: NoticesRoute,
  ContactRoute: ContactRoute,
  DealerInquiryRoute: DealerInquiryRoute,
  TabletInquiryRoute: TabletInquiryRoute,
  CareersAiInstructorRoute: CareersAiInstructorRoute,
  CareersDancersChoreographersRoute: CareersDancersChoreographersRoute,
  CareersAiVideoContentCreatorRoute: CareersAiVideoContentCreatorRoute,
  CareersActorsRoute: CareersActorsRoute,
  NewsMoripeSamsungB2bRoute: NewsMoripeSamsungB2bRoute,
  NewsDellaBalladProjectRoute: NewsDellaBalladProjectRoute,
  NoticesDemoSourcingRoute: NoticesDemoSourcingRoute,
  NoticesWebsiteLaunchRoute: NoticesWebsiteLaunchRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AirdropRoute: AirdropRoute,
  CertificatesRoute: CertificatesRoute,
  NftAdminRoute: NftAdminRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  LanguageRoute: LanguageRoute,
  ProfileRoute: ProfileRoute,
  ReferralRoute: ReferralRoute,
  TransactionsRoute: TransactionsRoute,

};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
