/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";

import { Route as TransactionsRouteImport } from "./routes/transactions";
import { Route as ReferralRouteImport } from "./routes/referral";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as LanguageRouteImport } from "./routes/language";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ConnectRouteImport } from "./routes/connect";
import { Route as AirdropRouteImport } from "./routes/airdrop";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";


const TransactionsRoute = TransactionsRouteImport.update({
  id: "/transactions",
  path: "/transactions",
  getParentRoute: () => rootRouteImport,
} as any);
const ReferralRoute = ReferralRouteImport.update({
  id: "/referral",
  path: "/referral",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const LanguageRoute = LanguageRouteImport.update({
  id: "/language",
  path: "/language",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ConnectRoute = ConnectRouteImport.update({
  id: "/connect",
  path: "/connect",
  getParentRoute: () => rootRouteImport,
} as any);
const AirdropRoute = AirdropRouteImport.update({
  id: "/airdrop",
  path: "/airdrop",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/admin": typeof AdminRoute;
  "/airdrop": typeof AirdropRoute;
  "/connect": typeof ConnectRoute;
  "/dashboard": typeof DashboardRoute;
  "/language": typeof LanguageRoute;
  "/profile": typeof ProfileRoute;
  "/referral": typeof ReferralRoute;
  "/transactions": typeof TransactionsRoute;

}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/admin": typeof AdminRoute;
  "/airdrop": typeof AirdropRoute;
  "/connect": typeof ConnectRoute;
  "/dashboard": typeof DashboardRoute;
  "/language": typeof LanguageRoute;
  "/profile": typeof ProfileRoute;
  "/referral": typeof ReferralRoute;
  "/transactions": typeof TransactionsRoute;

}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/admin": typeof AdminRoute;
  "/airdrop": typeof AirdropRoute;
  "/connect": typeof ConnectRoute;
  "/dashboard": typeof DashboardRoute;
  "/language": typeof LanguageRoute;
  "/profile": typeof ProfileRoute;
  "/referral": typeof ReferralRoute;
  "/transactions": typeof TransactionsRoute;

}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/admin"
    | "/airdrop"
    | "/connect"
    | "/dashboard"
    | "/language"
    | "/profile"
    | "/referral"
    | "/transactions"

  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/admin"
    | "/airdrop"
    | "/connect"
    | "/dashboard"
    | "/language"
    | "/profile"
    | "/referral"
    | "/transactions"

  id:
    | "__root__"
    | "/"
    | "/about"
    | "/admin"
    | "/airdrop"
    | "/connect"
    | "/dashboard"
    | "/language"
    | "/profile"
    | "/referral"
    | "/transactions"

  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  AdminRoute: typeof AdminRoute;
  AirdropRoute: typeof AirdropRoute;
  ConnectRoute: typeof ConnectRoute;
  DashboardRoute: typeof DashboardRoute;
  LanguageRoute: typeof LanguageRoute;
  ProfileRoute: typeof ProfileRoute;
  ReferralRoute: typeof ReferralRoute;
  TransactionsRoute: typeof TransactionsRoute;

}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {

    "/transactions": {
      id: "/transactions";
      path: "/transactions";
      fullPath: "/transactions";
      preLoaderRoute: typeof TransactionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/referral": {
      id: "/referral";
      path: "/referral";
      fullPath: "/referral";
      preLoaderRoute: typeof ReferralRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/language": {
      id: "/language";
      path: "/language";
      fullPath: "/language";
      preLoaderRoute: typeof LanguageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/connect": {
      id: "/connect";
      path: "/connect";
      fullPath: "/connect";
      preLoaderRoute: typeof ConnectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/airdrop": {
      id: "/airdrop";
      path: "/airdrop";
      fullPath: "/airdrop";
      preLoaderRoute: typeof AirdropRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AirdropRoute: AirdropRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  LanguageRoute: LanguageRoute,
  ProfileRoute: ProfileRoute,
  ReferralRoute: ReferralRoute,
  TransactionsRoute: TransactionsRoute,

};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
